### PR TITLE
fixes #13 , issues with query box width

### LINKED ISSUE #13: Query box doesn't have proper width
http://i.imgur.com/RvkSiTb.jpg

Edit: Probably because of this https://github.com/amasad/eHistory/commit/d77f8cce6365cb9ea3721046af6c3567101c68cd

Another quick edit: 

`width: calc(100% - 16px);` is giving "invalid property value"

### PR DESCRIPTION
**Pull request by masad-frost**

### CODE REVIEW

**Comment by amasad** [comment]
Thank you!

**Comment by amasad** [comment]
will release later today

**Comment by masad-frost** [comment]
Great. 

I'm trying to learn how to get snippets in history results, I'll let you know if I'm onto something.

**Comment by amasad** [comment]
Does the native chrome history still do that?

**Comment by masad-frost** [comment]
Yes it does. It was added not long ago.

**Comment by amasad** [comment]
Are you sure? I'm not able to get it to do that.

**Comment by masad-frost** [comment]
I just updated my Chromium, looks like the feature was removed. http://imgur.com/a/Zd47u 

I've been looking at a chromium repo with a revision that had it, and a more recent repo that didn't have, it seems like it wasn't totally removed, just commented out for the most part. Weird, it was a nice feature honestly. It might've even never made it to the official chrome build. 

I've got to sleep, I'll look more into it, and I'll get back to you.

**Comment by amasad** [comment]
It was in Chrome when I first written eHistory but I haven't seen it in a while. Will that's fine, since they didn't expose it through the API.
If you want something to work on: when you search for something in Chrome history and the keyword is in the title it will be highlighted in bold. How about do that for eHistory?

**Comment by masad-frost** [comment]
Sure, sounds great, I'm on it.

**Comment by amasad** [comment]
Let me know if you're stuck I can give you some pointers.

**Pull request merged**
